export const DEFAULT_SESSION_TTL_DAYS = 30;
export const DEFAULT_RESET_PASSWORD_TTL_MINUTES = 30;
export const DEFAULT_LOGIN_CODE_TTL_MINUTES = 10;
export const DEFAULT_LOGIN_CODE_RESEND_COOLDOWN_SECONDS = 60;
