export const DEFAULT_COUNTRY_CODE = 'US';

export const PUBLIC_DROPS_DEFAULT_LIMIT = 50;
export const PUBLIC_DROPS_MAX_LIMIT = 200;
export const PUBLIC_DROPS_FETCH_MULTIPLIER = 12;
export const PUBLIC_DROPS_FETCH_MAX_LIMIT = 2000;

export const PRICE_HISTORY_DEFAULT_LIMIT = 30;
export const PRICE_HISTORY_MAX_LIMIT = 3650;
